version: "3"
services:
  elasticsearch: # Elasticsearch Instance
    container_name: sardine_es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    volumes: # Persist ES data in seperate "esdata" volume
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
volumes:
  esdata:
